name: Build and Deploy Static Site to Hostinger

on:
  push:
    branches: [ "main" ]   # Trigger on main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js (updated for Vite and modern packages)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20   # ✅ Updated to Node 20

      # 3️⃣ Install dependencies and build
      - name: Install and build
        run: |
          npm ci || npm install
          chmod +x ./node_modules/.bin/vite   # ✅ ensure vite is executable
          npm run build     # outputs /build folder

      # 4️⃣ Deploy built files to production branch
      - name: Push build to production branch
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          cd build
          git init
          git config user.name "GitHub Actions"
          git config user.email "bhusaresanket08@gmail.com"
          git add .
          git commit -m "Auto deploy static site"
          git branch -M production
          git push --force "https://x-access-token:${PERSONAL_TOKEN}@github.com/Sank000/Adhane-Food-Solutionos.git"
